import type {
  AdminBanner,
  AdminCategory,
  AdminCustomer,
  AdminOrderDetail,
  AdminOrderRow,
  AdminRestaurantRow,
  AdminRider,
  Overview,
  PlatformSettings,
  User,
} from "./api";

export const mockAdminUser: User = {
  _id: "66d000000000000000000001",
  name: "Chowly Operations",
  email: "admin@chowly.app",
  phone: "+1 (555) 234-5678",
  role: "admin",
  isActive: true,
  createdAt: "2026-08-01T10:00:00.000Z",
  updatedAt: "2026-09-01T10:00:00.000Z",
};

export const mockOverview: Overview = {
  today: {
    orders: 42,
    revenue: 128450, // $1,284.50
    commission: 25690, // $256.90
    riderPayouts: 34500, // $345.00
    averageOrderValue: 3058, // $30.58
  },
  yesterday: {
    orders: 38,
    revenue: 114200,
    commission: 22840,
    riderPayouts: 31200,
    averageOrderValue: 3005,
  },
  series: [
    { date: "Mon", revenue: 84200, commission: 16840 },
    { date: "Tue", revenue: 95400, commission: 19080 },
    { date: "Wed", revenue: 112000, commission: 22400 },
    { date: "Thu", revenue: 104500, commission: 20900 },
    { date: "Fri", revenue: 145000, commission: 29000 },
    { date: "Sat", revenue: 168000, commission: 33600 },
    { date: "Sun", revenue: 128450, commission: 25690 },
  ],
  byStatus: [
    { status: "confirmed", count: 3 },
    { status: "preparing", count: 5 },
    { status: "ready", count: 4 },
    { status: "out_for_delivery", count: 6 },
    { status: "delivered", count: 24 },
  ],
  recent: [
    {
      _id: "ord_101",
      reference: "CH-2481",
      contactName: "Sarah Jenkins",
      restaurantName: "Burger Craft & Co.",
      total: 3450,
      status: "out_for_delivery",
      createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      _id: "ord_102",
      reference: "CH-2480",
      contactName: "Marcus Vance",
      restaurantName: "Napoli Woodfired Pizza",
      total: 4200,
      status: "ready",
      createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    },
    {
      _id: "ord_103",
      reference: "CH-2479",
      contactName: "Elena Rostova",
      restaurantName: "Tokyo Ramen House",
      total: 2850,
      status: "preparing",
      createdAt: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    },
    {
      _id: "ord_104",
      reference: "CH-2478",
      contactName: "David Miller",
      restaurantName: "El Molino Taqueria",
      total: 2200,
      status: "confirmed",
      createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    },
    {
      _id: "ord_105",
      reference: "CH-2477",
      contactName: "Amara Okonjo",
      restaurantName: "Green Bowl Organic",
      total: 3100,
      status: "delivered",
      createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    },
  ],
  activity: [
    {
      orderId: "ord_101",
      reference: "CH-2481",
      restaurantName: "Burger Craft & Co.",
      status: "out_for_delivery",
      note: "Rider Alex Taylor collected package",
      at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    {
      orderId: "ord_102",
      reference: "CH-2480",
      restaurantName: "Napoli Woodfired Pizza",
      status: "ready",
      note: "Kitchen marked order ready for dispatch",
      at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    {
      orderId: "ord_103",
      reference: "CH-2479",
      restaurantName: "Tokyo Ramen House",
      status: "preparing",
      note: "Confirmed by kitchen staff",
      at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
  ],
  liveOrders: 18,
};

export const mockOrders: AdminOrderRow[] = [
  {
    _id: "ord_101",
    reference: "CH-2481",
    contactName: "Sarah Jenkins",
    restaurantName: "Burger Craft & Co.",
    itemCount: 3,
    total: 3450,
    restaurantPayout: 2760,
    status: "out_for_delivery",
    paidAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    driverName: "Alex Taylor",
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    _id: "ord_102",
    reference: "CH-2480",
    contactName: "Marcus Vance",
    restaurantName: "Napoli Woodfired Pizza",
    itemCount: 2,
    total: 4200,
    restaurantPayout: 3360,
    status: "ready",
    paidAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    _id: "ord_103",
    reference: "CH-2479",
    contactName: "Elena Rostova",
    restaurantName: "Tokyo Ramen House",
    itemCount: 2,
    total: 2850,
    restaurantPayout: 2280,
    status: "preparing",
    paidAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
  },
  {
    _id: "ord_104",
    reference: "CH-2478",
    contactName: "David Miller",
    restaurantName: "El Molino Taqueria",
    itemCount: 4,
    total: 2200,
    restaurantPayout: 1760,
    status: "confirmed",
    paidAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
  },
  {
    _id: "ord_105",
    reference: "CH-2477",
    contactName: "Amara Okonjo",
    restaurantName: "Green Bowl Organic",
    itemCount: 1,
    total: 3100,
    restaurantPayout: 2480,
    status: "delivered",
    paidAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    driverName: "Jordan Lee",
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
];

export const mockOrderDetail: AdminOrderDetail = {
  _id: "ord_101",
  reference: "CH-2481",
  status: "out_for_delivery",
  createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  paidAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  contactName: "Sarah Jenkins",
  contactPhone: "+1 (555) 987-6543",
  restaurantName: "Burger Craft & Co.",
  restaurantAddress: "142 Market St, San Francisco, CA",
  deliveryAddress: {
    line1: "742 Evergreen Terrace",
    line2: "Apt 4B",
    city: "San Francisco",
    postcode: "94103",
    instructions: "Please ring apartment buzzer 4B.",
  },
  items: [
    {
      _id: "item_1",
      name: "Truffle Smash Double",
      quantity: 2,
      unitPrice: 1350,
      optionNames: ["Brioche Bun", "Extra Aged Cheddar"],
      note: "Sauce on side",
    },
    {
      _id: "item_2",
      name: "Rosemary Sea Salt Fries",
      quantity: 1,
      unitPrice: 550,
      optionNames: ["Large"],
    },
  ],
  subtotal: 3250,
  deliveryFee: 299,
  serviceFee: 199,
  total: 3748,
  commission: 650,
  commissionRate: 20,
  restaurantPayout: 2600,
  driver: {
    name: "Alex Taylor",
    phone: "+1 (555) 321-7654",
  },
  driverPayout: {
    base: 350,
    distance: 210,
    total: 560,
    distanceKm: 3.5,
  },
  includeCutlery: true,
  orderNote: "Leave at door if not answering.",
  statusHistory: [
    {
      _id: "st_1",
      status: "confirmed",
      at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      note: "Payment authorized via Stripe",
    },
    {
      _id: "st_2",
      status: "preparing",
      at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      note: "Sent to kitchen display",
    },
    {
      _id: "st_3",
      status: "ready",
      at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      note: "Packed and sealed",
    },
    {
      _id: "st_4",
      status: "out_for_delivery",
      at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      note: "Picked up by Alex Taylor",
    },
  ],
  estimatedDeliveryAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
};

export const mockRestaurants: AdminRestaurantRow[] = [
  {
    _id: "rest_1",
    name: "Burger Craft & Co.",
    slug: "burger-craft-co",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80",
    address: "142 Market St, San Francisco, CA",
    cuisines: ["Burgers", "American"],
    rating: 4.8,
    ratingCount: 312,
    prepTimeMinMinutes: 15,
    prepTimeMaxMinutes: 25,
    deliveryFee: 299,
    minOrder: 1500,
    commissionRate: 20,
    description: "Handcrafted artisan smash burgers made with 100% grass-fed Angus beef.",
    closesAt: "23:00",
    isOpen: true,
    freeDeliveryThreshold: 3500,
    isActive: true,
    ordersToday: 24,
  },
  {
    _id: "rest_2",
    name: "Napoli Woodfired Pizza",
    slug: "napoli-woodfired-pizza",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80",
    address: "88 Columbus Ave, San Francisco, CA",
    cuisines: ["Pizza", "Italian"],
    rating: 4.9,
    ratingCount: 428,
    prepTimeMinMinutes: 20,
    prepTimeMaxMinutes: 30,
    deliveryFee: 349,
    minOrder: 2000,
    commissionRate: 18,
    description: "Authentic Neapolitan sourdough pizza baked in a 900-degree Stefano Ferrara oven.",
    closesAt: "22:30",
    isOpen: true,
    freeDeliveryThreshold: 4000,
    isActive: true,
    ordersToday: 31,
  },
  {
    _id: "rest_3",
    name: "Tokyo Ramen House",
    slug: "tokyo-ramen-house",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80",
    address: "512 Geary St, San Francisco, CA",
    cuisines: ["Ramen", "Japanese"],
    rating: 4.7,
    ratingCount: 195,
    prepTimeMinMinutes: 15,
    prepTimeMaxMinutes: 25,
    deliveryFee: 299,
    minOrder: 1800,
    commissionRate: 20,
    description: "Slow-simmered 18-hour tonkotsu broth with handmade springy noodles and chashu.",
    closesAt: "22:00",
    isOpen: true,
    isActive: true,
    ordersToday: 19,
  },
  {
    _id: "rest_4",
    name: "El Molino Taqueria",
    slug: "el-molino-taqueria",
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop&q=80",
    address: "2410 Mission St, San Francisco, CA",
    cuisines: ["Mexican", "Tacos"],
    rating: 4.6,
    ratingCount: 160,
    prepTimeMinMinutes: 10,
    prepTimeMaxMinutes: 20,
    deliveryFee: 199,
    minOrder: 1200,
    commissionRate: 15,
    description: "Traditional street tacos, slow-cooked carnitas, and fresh made-to-order guacamole.",
    closesAt: "00:00",
    isOpen: true,
    isActive: true,
    ordersToday: 14,
  },
];

export const mockCategories: AdminCategory[] = [
  {
    _id: "cat_1",
    name: "Burgers",
    slug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80",
    backgroundColor: "#FEE2E2",
    sortOrder: 1,
    isActive: true,
    restaurantCount: 8,
    dishCount: 42,
  },
  {
    _id: "cat_2",
    name: "Pizza",
    slug: "pizza",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&auto=format&fit=crop&q=80",
    backgroundColor: "#FEF3C7",
    sortOrder: 2,
    isActive: true,
    restaurantCount: 6,
    dishCount: 38,
  },
  {
    _id: "cat_3",
    name: "Asian & Ramen",
    slug: "asian-ramen",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&auto=format&fit=crop&q=80",
    backgroundColor: "#DCFCE7",
    sortOrder: 3,
    isActive: true,
    restaurantCount: 11,
    dishCount: 64,
  },
  {
    _id: "cat_4",
    name: "Mexican",
    slug: "mexican",
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&auto=format&fit=crop&q=80",
    backgroundColor: "#F3E8FF",
    sortOrder: 4,
    isActive: true,
    restaurantCount: 5,
    dishCount: 29,
  },
];

export const mockRiders: AdminRider[] = [
  {
    _id: "rider_1",
    name: "Alex Taylor",
    email: "alex.rider@chowly.app",
    phone: "+1 (555) 321-7654",
    driverStatus: "approved",
    isOnline: true,
    isActive: true,
    rating: 4.9,
    ratingCount: 184,
    deliveries: 412,
    earnings: 284500, // $2,845.00
    activeDeliveries: 1,
    lastDeliveryAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    createdAt: "2026-06-15T08:30:00.000Z",
  },
  {
    _id: "rider_2",
    name: "Jordan Lee",
    email: "jordan.lee@chowly.app",
    phone: "+1 (555) 432-8765",
    driverStatus: "approved",
    isOnline: true,
    isActive: true,
    rating: 4.8,
    ratingCount: 142,
    deliveries: 289,
    earnings: 198200,
    activeDeliveries: 0,
    lastDeliveryAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    createdAt: "2026-07-02T11:00:00.000Z",
  },
  {
    _id: "rider_3",
    name: "Samir Patel",
    email: "driver@chowly.app",
    phone: "+1 (555) 543-9876",
    driverStatus: "approved",
    isOnline: false,
    isActive: true,
    rating: 4.95,
    ratingCount: 96,
    deliveries: 165,
    earnings: 112000,
    activeDeliveries: 0,
    lastDeliveryAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    createdAt: "2026-08-10T14:15:00.000Z",
  },
];

export const mockCustomers: AdminCustomer[] = [
  {
    _id: "cust_1",
    name: "Sarah Jenkins",
    email: "customer@chowly.app",
    phone: "+1 (555) 987-6543",
    isActive: true,
    orders: 14,
    totalSpent: 48600, // $486.00
    lastOrderAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    createdAt: "2026-06-20T09:00:00.000Z",
  },
  {
    _id: "cust_2",
    name: "Marcus Vance",
    email: "marcus.v@example.com",
    phone: "+1 (555) 876-5432",
    isActive: true,
    orders: 8,
    totalSpent: 26400,
    lastOrderAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    createdAt: "2026-07-15T15:30:00.000Z",
  },
];

export const mockBanners: AdminBanner[] = [
  {
    _id: "ban_1",
    title: "Free Delivery This Weekend",
    subtitle: "On all orders above $25 from premier local restaurants",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop&q=80",
    categorySlug: "burgers",
    isActive: true,
    sortOrder: 1,
    state: "active",
  },
  {
    _id: "ban_2",
    title: "Fresh Artisanal Pizza",
    subtitle: "Hand-stretched authentic woodfired crusts",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&auto=format&fit=crop&q=80",
    categorySlug: "pizza",
    isActive: true,
    sortOrder: 2,
    state: "active",
  },
];

export const mockSettings: PlatformSettings = {
  driverBasePay: 350, // $3.50
  driverPayPerKm: 60, // $0.60
  restaurantCommissionRate: 20, // 20%
  serviceFeeRate: 5, // 5%
  updatedAt: new Date().toISOString(),
};
